server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /
      suffix: .jsp

management:
  endpoints:
    web:
      exposure:
        include: env,health,info