server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /
      suffix: .jsp
logging:
  level:
    org:
      springframework:
        web: DEBUG
    ru:
      sanekesv:
        inovustest: DEBUG
